// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARufpXRf0PTmUN45TOuQNqbiPTsyN49O8',
    appId: '1:413091440773:android:1a55659c667e46526b61ec',
    messagingSenderId: '413091440773',
    projectId: 'quizappnew-a7cb4',
    databaseURL: 'https://quizappnew-a7cb4-default-rtdb.firebaseio.com',
    storageBucket: 'quizappnew-a7cb4.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2rcT4MP8N6c2Cg21dPR1vnDQDDGv9j4',
    appId: '1:413091440773:web:73a0b8c9ef7e04786b61ec',
    messagingSenderId: '413091440773',
    projectId: 'quizappnew-a7cb4',
    authDomain: 'quizappnew-a7cb4.firebaseapp.com',
    storageBucket: 'quizappnew-a7cb4.appspot.com',
    measurementId: 'G-T1528FMXC7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBX4xlrWwQ5wsQ-6xjrSjLLq4twnTxY2I',
    appId: '1:413091440773:ios:b2ca7f248f6c843b6b61ec',
    messagingSenderId: '413091440773',
    projectId: 'quizappnew-a7cb4',
    storageBucket: 'quizappnew-a7cb4.appspot.com',
    iosBundleId: 'com.example.quizapplicationnew',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBX4xlrWwQ5wsQ-6xjrSjLLq4twnTxY2I',
    appId: '1:413091440773:ios:b2ca7f248f6c843b6b61ec',
    messagingSenderId: '413091440773',
    projectId: 'quizappnew-a7cb4',
    storageBucket: 'quizappnew-a7cb4.appspot.com',
    iosBundleId: 'com.example.quizapplicationnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx2rcT4MP8N6c2Cg21dPR1vnDQDDGv9j4',
    appId: '1:413091440773:web:673ab4ee4221f4ca6b61ec',
    messagingSenderId: '413091440773',
    projectId: 'quizappnew-a7cb4',
    authDomain: 'quizappnew-a7cb4.firebaseapp.com',
    databaseURL: 'https://quizappnew-a7cb4-default-rtdb.firebaseio.com',
    storageBucket: 'quizappnew-a7cb4.appspot.com',
    measurementId: 'G-12RWL67S03',
  );

}